<a href="https://colab.research.google.com/github/mafumuto/EmKa_Akademi_Numpy-Pandas/blob/main/EmKa_Akademi_Practices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

1) Manuel değerleri el ile girerek 3 boyutlu bir array oluşturup bir değişkene atayın. Ardından 3 boyutlu olup olmadığına bakmak için dimension'ını kontrol edin
# Cevap:

In [ ]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr3d)
print('-------------------')
print(arr3d.shape)
arr3d.ndim

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
-------------------
(3, 2, 2)


3

2) 34, 40, 46, 52... 112 şeklinde devam eden 1 boyutlu bir array oluşturun.
#Cevap:

In [ ]:
np.arange(34, 113, 6)

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

3) 50-500 arasında lineer artış gösteren 91 tane tam sayıdan oluşan bir array oluşturun.(dtype'ı int olsun)
#Cevap:

In [ ]:
np.linspace(50, 500, 91, dtype= int)

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

4) 100(10^2) ile 10000(10^5) arasında logaritmik artış gösteren 8 sayıdan oluşan bir array oluşturun.
#Cevap:

In [ ]:
np.logspace(2, 5, 8, dtype= int)

array([   100,    268,    719,   1930,   5179,  13894,  37275, 100000])

5) 0-8 tam arasındaki ardışık tam sayılardan oluşan(0 ve 8 dahil toplam 9 değer) 3x3 shape'inde bir matris oluşturun.
#Cevap:

In [ ]:
arr_random = np.random.randint(0, 9, (3,3))
print(arr_random)
print('----------')
arr_random.shape

[[8 8 0]
 [7 7 4]
 [2 6 4]]
----------


(3, 3)

6) 6x6 formatında bir sıfır matrisi oluşturun. (dtype'ı int olsun)
#Cevap:

In [ ]:
arr_zero = np.zeros((6,6), dtype= int)
print(arr_zero)
arr_zero.shape

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


(6, 6)

7) 4x4 formatında bir bir matrisi oluşturun. (dtype'ı int olsun)
#Cevap:

In [ ]:
arr_one = np.ones((4,4), dtype = int)
print(arr_one)
arr_one.shape

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


(4, 4)

8) 8x8 formatında bir birim matris oluşturun. (Sadece sol köşegeni 1 geri kalan değerleri 0 olan matris'e birim matris deniyor.) (dtype'ı int olsun)
#Cevap:

In [ ]:
arr_eye = np.eye(8, 8, dtype= int)
print(arr_eye)
print(f"Shape and Data Type: {arr_eye.shape}, {arr_eye.dtype}")

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]
Shape and Data Type: (8, 8), int64


9) 5x5 formatında bir köşegen matrisi oluşturun (Sadece sol üstten sağ alta doğru olan köşegendeki değerleri 3 olsun diğer bütün değerleri 0) (Bunu henüz görmediniz ama birim matrise benziyor, sadece köşegen değerleri 1 değil 3 olacak. Bir şeyler düşünün)
#Cevap:

In [ ]:
a = np.linspace(3, 3 , 5, dtype= int)
np.diag(a)

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

10) np.random modülünden uygun fonksiyonu kullanarak 0-1 arasında toplam 6 tane değerden oluşan 1 boyutlu bir array oluşturun.
#Cevap:

In [ ]:
np.random.random_sample(6)

array([0.16971692, 0.5525381 , 0.86531427, 0.47421508, 0.4396164 ,
       0.47747887])

11) np.random modülünden uygun fonksiyonu kullanarak 50-100 arasındaki(50 ve 100 dahil) tam sayılardan 10 tanesiyle oluşan (5,2) shape'inde bir array oluşturun. Ardından bu arrayin shape'ini kontrol edin.
#Cevap:

In [ ]:
arr_ten_random = np.random.randint(50, 100, (5, 2))
print(f"{arr_ten_random}\nShape: {arr_ten_random.shape}")

[[61 55]
 [81 80]
 [65 95]
 [62 56]
 [54 93]]
Shape: (5, 2)


12) np.random modülünden uygun fonksiyonu kullanarak 100-1000(1000 dahil değil) arasındaki tam sayılardan rastgele 50 tanesinden oluşan (2,5,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in dimension'ını(boyutunu) ve shape'ini kontrol edin.
#Cevap:

In [ ]:
arr_random3d = np.random.randint(100, 1000, size=(2, 5, 5))
print(f"Array: {arr_random3d}\nDimension: {arr_random3d.ndim}\nShape: {arr_random3d.shape}")

Array: [[[315 893 894 492 330]
  [991 880 611 189 538]
  [338 824 203 731 182]
  [921 121 237 237 350]
  [689 985 144 186 996]]

 [[898 335 769 494 552]
  [969 640 417 353 357]
  [685 120 539 134 945]
  [196 187 859 247 296]
  [971 782 978 611 715]]]
Dimension: 3
Shape: (2, 5, 5)


13) np.random modülünden uygun fonksiyonu kullanarak 0-100(0 ve 100 dahil) arasındaki tam sayılardan 10 tane seçerek bir array oluşturun. Bu array'in maximum, mininmum değerlerine ve bu değerlerin indexlerine bakın.

#Cevap:

In [ ]:
arr_random1d = np.random.randint(0, 101, size=(10))
print(f"Array: {arr_random1d}\n",
      f"Maximum Value and Index: {arr_random1d.max()}-{arr_random1d.argmax()}\n",
      f"Minimum Value and Index: {arr_random1d.min()}-{arr_random1d.argmin()}\n",
      f"Dimension and Shape: {arr_random1d.ndim}-{arr_random1d.shape}")

Array: [33 84 94 63 45 81  9 33  3 88]
 Maximum Value and Index: 94-2
 Minimum Value and Index: 3-8
 Dimension and Shape: 1-(10,)


14) np.random modülünden uygun fonksiyonu kullanarak 300-500(300 ve 500 dahil) arasındaki tam sayılardan 20 tane seçerek (2,2,5) shape'inde 3 boyutlu bir array oluşturun. Ardından bu array'in içindeki 20 tam sayı arasından maximum ve minimum değerleri manuel olarak tespit edin ve indexleme yaparak çekmeye çalışın.
#Cevap:

In [ ]:
arr_random3d_2 = np.random.randint(300,500, (2,2,5))
arr_random3d_2

array([[[376, 363, 488, 312, 368],
        [300, 443, 427, 413, 438]],

       [[335, 437, 383, 309, 352],
        [380, 319, 305, 467, 457]]])

In [ ]:
print(f"Maximum Value: {arr_random3d_2[0,0,2]}\n",
      f"Minimum Value: {arr_random3d_2[0,1,0]}")

Maximum Value: 488
 Minimum Value: 300


15) 0-50(50 dahil) arasındaki ardışık tam sayılardan oluşan bir array oluşturun. Ardından bu arrayin 20. ve 35. indexleri arasındaki değerleri 500'e eşitleyin ve yeni oluşan array'i ekrana yazdırarak broadcasting işleminin yapılıp yapılmadığını test edin.

#Cevap:

In [ ]:
arr_orginal = np.arange(0, 51, dtype= int)
print(arr_orginal)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]


In [ ]:
arr_orginal[20:35] = 500
print(arr_orginal)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19 500 500 500 500 500 500 500 500 500 500 500 500 500 500 500  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50]
